/*
--- Ailey & Bailey Canvas ---
File: script.js
Version: 6.3 (Upgraded Navigation Scanner)
Architect: [Username] & System Architect Ailey
Description: Upgraded the navigation scanner to include list-based subheadings from the main content for a richer ToC. This script is designed to "hydrate" the HTML content block generated by the AI.

// [ARCHITECT'S NOTE]
// This script requires user configuration in two places to function correctly:
// 1. Firebase Configuration: The `initializeFirebase` function looks for a `__firebase_config` variable.
//    For static hosting on GitHub, you must replace this with your actual Firebase config object.
// 2. Gemini API Key: The `handleChatSend` function has an empty `apiKey` variable.
//    You MUST insert your Google AI Studio API key there for the chat functionality to work.
*/

document.addEventListener('DOMContentLoaded', function () {
    // --- 1. Element Declarations ---
    const learningContent = document.getElementById('learning-content');
    const wrapper = document.querySelector('.wrapper');
    const body = document.body;
    const clockElement = document.getElementById('real-time-clock');
    const selectionPopover = document.getElementById('selection-popover');
    const popoverAskAi = document.getElementById('popover-ask-ai');
    const popoverAddNote = document.getElementById('popover-add-note');
    const tocToggleBtn = document.getElementById('toc-toggle-btn');
    const quizModalOverlay = document.getElementById('quiz-modal-overlay');
    const quizContainer = document.getElementById('quiz-container');
    const quizSubmitBtn = document.getElementById('quiz-submit-btn');
    const quizResults = document.getElementById('quiz-results');
    const startQuizBtn = document.getElementById('start-quiz-btn');
    const chatModeSelector = document.getElementById('chat-mode-selector');
    const deleteHistoryBtn = document.getElementById('delete-history-btn');
    const chatPanel = document.getElementById('chat-panel');
    const chatForm = document.getElementById('chat-form');
    const chatInput = document.getElementById('chat-input');
    const chatMessages = document.getElementById('chat-messages');
    const chatSendBtn = document.getElementById('chat-send-btn');
    const notesAppPanel = document.getElementById('notes-app-panel');
    const noteListView = document.getElementById('note-list-view');
    const noteEditorView = document.getElementById('note-editor-view');
    const notesList = document.getElementById('notes-list');
    const searchInput = document.getElementById('search-input');
    const addNewNoteBtn = document.getElementById('add-new-note-btn');
    const backToListBtn = document.getElementById('back-to-list-btn');
    const noteTitleInput = document.getElementById('note-title-input');
    const noteContentTextarea = document.getElementById('note-content-textarea');
    const autoSaveStatus = document.getElementById('auto-save-status');
    const formatToolbar = document.querySelector('.format-toolbar');
    const linkTopicBtn = document.getElementById('link-topic-btn');
    const exportNotesBtn = document.getElementById('export-notes-btn');
    const customModal = document.getElementById('custom-modal');
    const modalMessage = document.getElementById('modal-message');
    const modalConfirmBtn = document.getElementById('modal-confirm-btn');
    const modalCancelBtn = document.getElementById('modal-cancel-btn');
    const promptModalOverlay = document.getElementById('prompt-modal-overlay');
    const customPromptInput = document.getElementById('custom-prompt-input');
    const promptSaveBtn = document.getElementById('prompt-save-btn');
    const promptCancelBtn = document.getElementById('prompt-cancel-btn');
    const editCustomPromptBtn = document.getElementById('edit-custom-prompt-btn');
    const themeToggle = document.getElementById('theme-toggle');
    const chatToggleBtn = document.getElementById('chat-toggle-btn');
    const notesAppToggleBtn = document.getElementById('notes-app-toggle-btn');

    // --- 2. State Management ---
    let db, notesCollection, chatCollectionRef;
    let currentUser = null;
    const appId = typeof __app_id !== 'undefined' ? __app_id : 'AileyBailey_Global_Space';
    let storageKey = 'learningNote-' + (document.title || 'default-page');
    let localNotesCache = [];
    let currentNoteId = null;
    let unsubscribeFromNotes = null;
    let debounceTimer = null;
    let chatHistories = { default: [], socratic: [], interview: [], custom: [] };
    let selectedMode = 'default';
    let customPrompt = localStorage.getItem('customTutorPrompt') || '너는 AI 튜터야. 사용자의 모든 질문에 답변해줘.';
    let unsubscribeFromChat = null;
    let currentQuizData = null;

    // --- 3. Function Definitions (in logical order) ---

    // Firebase
    async function initializeFirebase() {
        try {
            // [ARCHITECT'S NOTE] For GitHub hosting, replace the conditional logic with your actual Firebase config object.
            // Example: const firebaseConfig = { apiKey: "...", authDomain: "...", ... };
            const firebaseConfig = typeof __firebase_config !== 'undefined' ? JSON.parse(__firebase_config) : null;
            const initialAuthToken = typeof __initial_auth_token !== 'undefined' ? __initial_auth_token : null;

            if (!firebaseConfig) { throw new Error("Firebase config not found. Please configure it in script.js."); }
            if (!firebase.apps.length) { firebase.initializeApp(firebaseConfig); }
            const auth = firebase.auth();
            db = firebase.firestore();
            if (initialAuthToken) {
                await auth.signInWithCustomToken(initialAuthToken).catch(async (err) => {
                   console.warn("Custom token sign-in failed, trying anonymous.", err);
                   await auth.signInAnonymously();
                });
            } else {
                await auth.signInAnonymously();
            }
            currentUser = auth.currentUser;
            if (currentUser) {
                notesCollection = db.collection(`artifacts/${appId}/users/${currentUser.uid}/notes`);
                listenToNotes();
                chatCollectionRef = db.collection(`artifacts/${appId}/users/${currentUser.uid}/chatHistories`).doc(storageKey);
                listenToChatHistory();
            }
        } catch (error) {
            console.error("Firebase Initialization or Auth Failed:", error);
            if (notesList) notesList.innerHTML = '<div>Failed to load cloud notes.</div>';
            if (chatMessages) chatMessages.innerHTML = '<div>Failed to connect to AI Tutor.</div>';
        }
    }

    // UI & Utilities
    function updateClock() {
        if (!clockElement) return;
        const now = new Date();
        const options = { timeZone: 'Asia/Seoul', year: 'numeric', month: 'long', day: 'numeric', weekday: 'long', hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' };
        clockElement.textContent = now.toLocaleString('ko-KR', options);
    }
    
    function initializeTooltips() {
        const keywordChips = document.querySelectorAll('.keyword-chip');
        keywordChips.forEach(chip => {
            const tooltipText = chip.dataset.tooltip;
            if (tooltipText) {
                chip.classList.add('has-tooltip');
                const tooltipElement = chip.querySelector('.tooltip');
                if (tooltipElement) {
                    tooltipElement.textContent = tooltipText;
                }
            }
        });

        const inlineHighlights = document.querySelectorAll('.content-section strong[data-tooltip]');
        inlineHighlights.forEach(highlight => {
            const tooltipText = highlight.dataset.tooltip;
            if(tooltipText && !highlight.querySelector('.tooltip')) {
                 highlight.classList.add('has-tooltip');
                 const tooltipElement = document.createElement('span');
                 tooltipElement.className = 'tooltip';
                 tooltipElement.textContent = tooltipText;
                 highlight.appendChild(tooltipElement);
            }
        });
    }

    function makePanelDraggable(panelElement) {
        if(!panelElement) return;
        const header = panelElement.querySelector('.panel-header');
        if(!header) return;
        let isDragging = false, offset = { x: 0, y: 0 };
        const onMouseMove = (e) => { if (isDragging) { panelElement.style.left = (e.clientX + offset.x) + 'px'; panelElement.style.top = (e.clientY + offset.y) + 'px'; } };
        const onMouseUp = () => { 
            isDragging = false; 
            panelElement.classList.remove('is-dragging');
            document.removeEventListener('mousemove', onMouseMove); 
            document.removeEventListener('mouseup', onMouseUp); 
        };
        header.addEventListener('mousedown', e => {
            if (e.target.closest('button, input, .close-btn, #delete-history-btn, #chat-mode-selector')) return;
            isDragging = true;
            panelElement.classList.add('is-dragging');
            offset = { x: panelElement.offsetLeft - e.clientX, y: panelElement.offsetTop - e.clientY };
            document.addEventListener('mousemove', onMouseMove);
            document.addEventListener('mouseup', onMouseUp);
        });
    }
    
    function togglePanel(panelElement, forceShow = null) {
        if (!panelElement) return;
        const show = forceShow !== null ? forceShow : panelElement.style.display !== 'flex';
        panelElement.style.display = show ? 'flex' : 'none';
    }

    /* --- MODIFIED: UPGRADED NAVIGATION SCANNER --- */
    function setupNavigator() {
        const scrollNav = document.getElementById('scroll-nav');
        if (!scrollNav || !learningContent) return;
        
        const headers = learningContent.querySelectorAll('h2, #section-3 ul li > strong, #section-3 h3 > strong');
        
        if (headers.length === 0) {
            scrollNav.style.display = 'none';
            if(wrapper) wrapper.classList.add('toc-hidden');
            return;
        }
        scrollNav.style.display = 'block';
        if(wrapper) wrapper.classList.remove('toc-hidden');

        const navList = document.createElement('ul');
        headers.forEach((header, index) => {
            let targetElement;
            let isSubheading = false;
            if (header.tagName === 'H2') {
                targetElement = header.closest('.content-section');
            } else { 
                targetElement = header.closest('li, h3');
                isSubheading = true;
            }

            if (targetElement && !targetElement.id) {
                targetElement.id = `nav-target-${index}`;
            }
            
            if (targetElement) {
                const listItem = document.createElement('li');
                const link = document.createElement('a');
                
                let navText = header.textContent.trim();
                const maxLen = 25;
                if (navText.length > maxLen) {
                    navText = navText.substring(0, maxLen - 3) + '...';
                }
                link.textContent = navText;
                link.href = `#${targetElement.id}`;

                if (isSubheading) {
                    link.style.paddingLeft = '25px';
                    link.style.fontSize = '0.9em';
                }
                
                listItem.appendChild(link);
                navList.appendChild(listItem);
            }
        });
        scrollNav.innerHTML = '<h3>학습 내비게이션</h3>';
        scrollNav.appendChild(navList);

        const links = scrollNav.querySelectorAll('a');
        const observer = new IntersectionObserver(entries => {
            entries.forEach(entry => {
                const id = entry.target.getAttribute('id');
                const navLink = scrollNav.querySelector(`a[href="#${id}"]`);
                if (navLink && entry.isIntersecting && entry.intersectionRatio > 0.5) {
                    links.forEach(l => l.classList.remove('active'));
                    navLink.classList.add('active');
                }
            });
        }, { rootMargin: "0px 0px -70% 0px", threshold: 0.6 });

        headers.forEach(header => {
            const targetElement = header.tagName === 'H2' ? header.closest('.content-section') : header.closest('li, h3');
            if (targetElement) {
                observer.observe(targetElement);
            }
        });
    }
    /* --- END OF MODIFICATION --- */


    // Modals
    function openPromptModal() {
        if (customPromptInput) customPromptInput.value = customPrompt;
        if (promptModalOverlay) promptModalOverlay.style.display = 'flex';
    }
    function closePromptModal() {
        if (promptModalOverlay) promptModalOverlay.style.display = 'none';
    }
    function saveCustomPrompt() {
        if (customPromptInput) {
            customPrompt = customPromptInput.value;
            localStorage.setItem('customTutorPrompt', customPrompt);
            closePromptModal();
        }
    }
    function showModal(message, onConfirm) {
        if (!customModal || !modalMessage || !modalConfirmBtn || !modalCancelBtn) return;
        modalMessage.textContent = message;
        customModal.style.display = 'flex';
        modalConfirmBtn.onclick = () => { onConfirm(); customModal.style.display = 'none'; };
        modalCancelBtn.onclick = () => { customModal.style.display = 'none'; };
    }

    // Chat
    function generateTutorPrompt(mode, query) {
        let basePrompt = "";
        switch(mode) {
            case 'socratic': basePrompt = "너는 소크라테스야. 사용자의 질문에 직접 답하지 말고, 계속해서 질문을 던져 사용자가 스스로 답을 찾도록 유도해줘."; break;
            case 'interview': basePrompt = "너는 압박 면접관이야. 사용자의 답변에 대해 날카롭게 꼬리 질문을 던져줘."; break;
            case 'custom': basePrompt = customPrompt; break;
            default: basePrompt = "너는 '에일리'와 '베일리'라는 두 인격을 가진 AI 튜터야. 먼저 다정한 코치 '에일리'가 되어 사용자의 질문에 친절하게 답해줘(😊 이모지 사용). 그 다음, 답변과 관련된 비판적 사고를 유도하는 날카로운 질문을 '베일리'가 되어 던져줘(😎, 😒 이모지 사용). 에일리의 답변과 베일리의 질문은 반드시 ---CHALLENGE--- 문자열로 구분해야 해.";
        }
        const toneMandate = "너는 지금부터 친한 친구에게 말하는 것처럼, 반드시 친근한 반말(informal Korean)으로만 대화해야 해. '안녕하세요' 같은 존댓말은 절대 사용하면 안 돼.";
        return `${basePrompt} ${toneMandate} 다음 질문에 답변해줘: "${query}"`;
    }
    async function handleChatSend() {
        if (!chatInput || !chatSendBtn) return;
        const userQuery = chatInput.value.trim();
        if (!userQuery) return;
        chatInput.disabled = true;
        chatSendBtn.disabled = true;

        const currentHistory = chatHistories[selectedMode] || [];
        currentHistory.push({ role: 'user', content: userQuery, timestamp: new Date().toISOString() });
        renderChatHistory(selectedMode);
        
        const aiMessageDiv = document.createElement('div');
        aiMessageDiv.className = 'chat-message ai';
        aiMessageDiv.innerHTML = '<div class="loading-indicator">AI is generating a response...</div>';
        if(chatMessages) chatMessages.appendChild(aiMessageDiv);

        // [ARCHITECT'S NOTE] You MUST insert your Google AI Studio API key here.
        const apiKey = ""; // <--- PASTE YOUR API KEY HERE
        const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${apiKey}`;
        const payload = {
            contents: [{ role: "user", parts: [{ text: generateTutorPrompt(selectedMode, userQuery) }] }]
        };

        try {
            const response = await fetch(apiUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });
            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(`API Error: ${response.status} ${response.statusText} - ${errorData.error.message}`);
            }
            const result = await response.json();
            
            let aiResponse = "I'm sorry, I encountered a problem generating a response. 😥";
            if (result.candidates && result.candidates.length > 0 && result.candidates[0].content && result.candidates[0].content.parts && result.candidates[0].content.parts.length > 0) {
                aiResponse = result.candidates[0].content.parts[0].text;
            }
            
            const [aileyPart, baileyPart] = aiResponse.split('---CHALLENGE---');
            currentHistory.push({ role: 'ai', content: aileyPart.trim(), timestamp: new Date().toISOString() });
            if (baileyPart) {
                currentHistory.push({ role: 'bailey', content: baileyPart.trim(), timestamp: new Date().toISOString() });
            }
            await saveChatHistory();
            renderChatHistory(selectedMode);
        } catch (error) {
            console.error("AI API Error:", error);
            currentHistory.push({ role: 'ai', content: `An error occurred: ${error.message}`, timestamp: new Date().toISOString() });
            renderChatHistory(selectedMode);
        } finally {
            chatInput.disabled = false;
            chatSendBtn.disabled = false;
            chatInput.value = '';
            chatInput.style.height = 'auto';
            chatInput.focus();
        }
    }
    function renderChatHistory(mode) {
        if (!chatMessages) return;
        chatMessages.innerHTML = '';
        const history = chatHistories[mode] || [];
        history.forEach(msg => {
            const msgDiv = document.createElement('div');
            msgDiv.className = `chat-message ${msg.role}`;
            if(msg.role === 'bailey') msgDiv.classList.add('ai', 'bailey-challenge');
            const contentDiv = document.createElement('div');
            contentDiv.textContent = msg.content;
            msgDiv.appendChild(contentDiv);
            if (msg.timestamp) {
                const timeDiv = document.createElement('div');
                timeDiv.className = 'chat-timestamp';
                timeDiv.textContent = new Date(msg.timestamp).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' });
                msgDiv.appendChild(timeDiv);
            }
            if(msg.role === 'ai' || msg.role === 'bailey') {
                const sendToNoteBtn = document.createElement('button');
                sendToNoteBtn.className = 'send-to-note-btn';
                sendToNoteBtn.textContent = 'Send to Note';
                sendToNoteBtn.onclick = (e) => {
                    addNote(`[AI Tutor] ${msg.content}`);
                    e.target.textContent = '✅ Sent';
                    e.target.disabled = true;
                };
                contentDiv.appendChild(sendToNoteBtn);
            }
            chatMessages.appendChild(msgDiv);
        });
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }
    async function listenToChatHistory() {
        if (!chatCollectionRef) return;
        if (unsubscribeFromChat) unsubscribeFromChat();
        unsubscribeFromChat = chatCollectionRef.onSnapshot(doc => {
            if (doc.exists) {
                const data = doc.data();
                chatHistories = { ...{ default: [], socratic: [], interview: [], custom: [] }, ...data };
            } else {
                chatHistories = { default: [], socratic: [], interview: [], custom: [] };
            }
            renderChatHistory(selectedMode);
        }, error => console.error("Chat history listener error:", error));
    }
    async function saveChatHistory() {
        if (chatCollectionRef) {
            try { await chatCollectionRef.set(chatHistories); } 
            catch (error) { console.error("Failed to save chat history:", error); }
        }
    }

    // Notes
    function listenToNotes() {
        if (!notesCollection) return;
        if (unsubscribeFromNotes) unsubscribeFromNotes();
        unsubscribeFromNotes = notesCollection.onSnapshot(snapshot => {
            localNotesCache = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
            renderNoteList();
        }, error => { console.error("Note real-time listener error:", error); });
    }
    function renderNoteList() {
        if (!notesList || !searchInput) return;
        const searchTerm = searchInput.value.toLowerCase();
        const filteredNotes = localNotesCache.filter(note => (note.title && note.title.toLowerCase().includes(searchTerm)) || (note.content && note.content.toLowerCase().includes(searchTerm)));
        filteredNotes.sort((a, b) => {
            if (a.isPinned && !b.isPinned) return -1;
            if (!a.isPinned && b.isPinned) return 1;
            return (b.updatedAt?.toMillis() || 0) - (a.updatedAt?.toMillis() || 0);
        });
        notesList.innerHTML = '';
        if (filteredNotes.length === 0) {
            notesList.innerHTML = '<div>No notes to display.</div>';
            return;
        }
        filteredNotes.forEach(note => {
            const item = document.createElement('div');
            item.className = 'note-item';
            item.dataset.id = note.id;
            if (note.isPinned) item.classList.add('pinned');
            const date = note.updatedAt ? new Date(note.updatedAt.toMillis()).toLocaleString() : 'No date';
            item.innerHTML = `<div class="note-item-content"><div class="note-item-title">${note.title || 'Untitled'}</div><div class="note-item-date">${date}</div></div><div class="note-item-actions"><button class="item-action-btn pin-btn ${note.isPinned ? 'pinned-active' : ''}" title="Pin">${note.isPinned ? '📌' : '📍'}</button><button class="item-action-btn delete-btn" title="Delete">🗑️</button></div>`;
            notesList.appendChild(item);
        });
    }
    async function addNote(initialContent = '') {
        if (!notesCollection) return;
        try {
            const newNoteRef = await notesCollection.add({
                title: 'New Note', content: initialContent, isPinned: false,
                createdAt: firebase.firestore.FieldValue.serverTimestamp(),
                updatedAt: firebase.firestore.FieldValue.serverTimestamp()
            });
            openNoteEditor(newNoteRef.id);
        } catch (error) { console.error("Failed to add new note:", error); }
    }
    function saveNote() {
        if (debounceTimer) clearTimeout(debounceTimer);
        if (!currentNoteId || !notesCollection) return;
        const noteData = { title: noteTitleInput.value, content: noteContentTextarea.value, updatedAt: firebase.firestore.FieldValue.serverTimestamp() };
        notesCollection.doc(currentNoteId).update(noteData).then(() => updateStatus('Saved ✓', true)).catch(error => { console.error("Failed to save note:", error); updateStatus('Save failed ❌', false); });
    }
    function handleDeleteRequest(noteId) {
        showModal('Are you sure you want to permanently delete this note?', () => {
            if (notesCollection) notesCollection.doc(noteId).delete().catch(error => console.error("Failed to delete note:", error));
        });
    }
    async function togglePin(noteId) {
        if (!notesCollection) return;
        const note = localNotesCache.find(n => n.id === noteId);
        if (note) await notesCollection.doc(noteId).update({ isPinned: !note.isPinned });
    }
    function exportNotes() {
        const dataStr = JSON.stringify(localNotesCache, null, 2);
        const blob = new Blob([dataStr], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = 'my-notes.json'; a.click();
        URL.revokeObjectURL(url);
    }
    function switchView(viewName) {
        if (viewName === 'editor') {
            if(noteListView) noteListView.classList.remove('active');
            if(noteEditorView) noteEditorView.classList.add('active');
        } else {
            if(noteEditorView) noteEditorView.classList.remove('active');
            if(noteListView) noteListView.classList.add('active');
            currentNoteId = null;
        }
    }
    function openNoteEditor(noteId) {
        const note = localNotesCache.find(n => n.id === noteId);
        if (note && noteTitleInput && noteContentTextarea) {
            currentNoteId = noteId;
            noteTitleInput.value = note.title || '';
            noteContentTextarea.value = note.content || '';
            switchView('editor');
        }
    }
    function updateStatus(message, success) {
        if (!autoSaveStatus) return;
        autoSaveStatus.textContent = message;
        autoSaveStatus.style.color = success ? 'lightgreen' : 'lightcoral';
        setTimeout(() => { autoSaveStatus.textContent = ''; }, 2000);
    }
    function applyFormat(format) {
        if (!noteContentTextarea) return;
        const start = noteContentTextarea.selectionStart;
        const end = noteContentTextarea.selectionEnd;
        const selectedText = noteContentTextarea.value.substring(start, end);
        const marker = format === 'bold' ? '**' : (format === 'italic' ? '*' : '`');
        const newText = `${noteContentTextarea.value.substring(0, start)}${marker}${selectedText}${marker}${noteContentTextarea.value.substring(end)}`;
        noteContentTextarea.value = newText;
        noteContentTextarea.focus();
    }
    
    // Quiz
    async function startQuiz() {
        if (!quizModalOverlay) return;
        const keywords = Array.from(document.querySelectorAll('.keyword-chip')).map(k => k.textContent.trim()).join(', ');
        if (!keywords) { 
            showModal("No keywords found to generate a quiz.", () => { if(quizModalOverlay) quizModalOverlay.style.display = 'none'; });
            return;
        }
        // This is a placeholder as AI generation is handled in the main prompt context.
        // For a real application, you would make an API call here.
        const prompt = `Based on the following keywords, create a 3-question multiple-choice quiz: ${keywords}. Each question must have 4 options. The output MUST be in the following JSON format, with no other explanations.\n\n{"questions": [{"question": "...", "options": [...], "answer": "..."}, ...]}`;
        if (quizContainer) quizContainer.innerHTML = '<div class="loading-indicator">Generating quiz...</div>';
        if (quizResults) quizResults.innerHTML = '';
        quizModalOverlay.style.display = 'flex';
        try {
            // Using a mock response for demonstration
            const aiResponse = await new Promise(resolve => setTimeout(() => resolve(JSON.stringify({
                "questions": [
                    {"question": "(e.g) What was the core reform institution established by King Jeongjo to nurture young talent and research policies?", "options": ["Hall of Worthies", "Jangyongyeong", "Kyujanggak", "Sungkyunkwan"], "answer": "Kyujanggak"},
                    {"question": "(e.g) What was King Jeongjo's economic policy that abolished merchants' monopoly rights and guaranteed free commercial activities?", "options": ["Rank Land Law", "Daedongbeop", "Gyunyeokbeop", "Shin-Hae Tong-Gong"], "answer": "Shin-Hae Tong-Gong"},
                    {"question": "(e.g) What is the structure that embodies King Jeongjo's filial piety and reform will, where the latest science and technology such as Jeong Yak-yong's Geojunggi were mobilized?", "options": ["Gyeongbok Palace", "Changdeok Palace", "Hwaseong Fortress", "Namhansanseong"], "answer": "Hwaseong Fortress"}
                ]
            })), 1000));
            currentQuizData = JSON.parse(aiResponse);
            renderQuiz(currentQuizData);
        } catch (e) {
            if (quizContainer) quizContainer.innerHTML = 'Failed to generate quiz. Please try again.';
            console.error("Invalid quiz JSON", e);
        }
    }
    function renderQuiz(data) {
        if (!quizContainer || !data || !data.questions) return;
        quizContainer.innerHTML = '';
        data.questions.forEach((q, index) => {
            const questionBlock = document.createElement('div');
            questionBlock.className = 'quiz-question-block';
            const questionText = document.createElement('p');
            questionText.textContent = `${index + 1}. ${q.question}`;
            const optionsDiv = document.createElement('div');
            optionsDiv.className = 'quiz-options';
            q.options.forEach(option => {
                const label = document.createElement('label');
                const radio = document.createElement('input');
                radio.type = 'radio';
                radio.name = `question-${index}`;
                radio.value = option;
                label.appendChild(radio);
                label.appendChild(document.createTextNode(` ${option}`));
                optionsDiv.appendChild(label);
            });
            questionBlock.appendChild(questionText);
            questionBlock.appendChild(optionsDiv);
            quizContainer.appendChild(questionBlock);
        });
    }

    // --- 4. Global Initialization ---
    function initialize() {
        if (!body || !wrapper) {
            console.error("Core layout elements not found. Initialization aborted.");
            return;
        }
        
        updateClock();
        setInterval(updateClock, 1000);

        initializeTooltips();
        
        makePanelDraggable(chatPanel);
        makePanelDraggable(notesAppPanel);

        // Event Listeners
        if (themeToggle) themeToggle.addEventListener('click', () => {
            body.classList.toggle('dark-mode');
            themeToggle.textContent = body.classList.contains('dark-mode') ? '☀️' : '🌙';
        });
        if (tocToggleBtn) tocToggleBtn.addEventListener('click', () => {
            wrapper.classList.toggle('toc-hidden');
            if(clockElement) clockElement.classList.toggle('tucked');
        });
        if (chatToggleBtn) chatToggleBtn.addEventListener('click', () => togglePanel(chatPanel));
        if (chatPanel) chatPanel.querySelector('.close-btn').addEventListener('click', () => togglePanel(chatPanel, false));
        if (notesAppToggleBtn) notesAppToggleBtn.addEventListener('click', () => togglePanel(notesAppPanel));
        if (chatForm) chatForm.addEventListener('submit', e => { e.preventDefault(); handleChatSend(); });
        if (chatInput) chatInput.addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleChatSend(); } });
        if (deleteHistoryBtn) deleteHistoryBtn.addEventListener('click', async () => {
            showModal(`Are you sure you want to delete the chat history for '${selectedMode}' mode? This cannot be undone.`, async () => {
                chatHistories[selectedMode] = [];
                await saveChatHistory();
                renderChatHistory(selectedMode);
            });
        });
        if (promptSaveBtn) promptSaveBtn.addEventListener('click', saveCustomPrompt);
        if (promptCancelBtn) promptCancelBtn.addEventListener('click', closePromptModal);
        if (startQuizBtn) startQuizBtn.addEventListener('click', startQuiz);
        if (quizSubmitBtn) quizSubmitBtn.addEventListener('click', () => {
            if (!currentQuizData || !quizResults) return;
            let score = 0;
            let allAnswered = true;
            currentQuizData.questions.forEach((q, index) => {
                const selected = document.querySelector(`input[name="question-${index}"]:checked`);
                if (!selected) { allAnswered = false; }
            });
            if (!allAnswered) {
                quizResults.textContent = "Please answer all questions!";
                quizResults.style.color = 'orange';
                return;
            }
            currentQuizData.questions.forEach((q, index) => {
                const selected = document.querySelector(`input[name="question-${index}"]:checked`);
                const questionBlock = document.querySelectorAll('.quiz-question-block')[index];
                const labels = questionBlock.querySelectorAll('label');
                labels.forEach(label => {
                    const radio = label.querySelector('input');
                    if (radio.value === q.answer) {
                        label.style.color = 'lightgreen';
                        label.style.fontWeight = 'bold';
                    }
                    if (radio.checked && radio.value !== q.answer) {
                        label.style.color = 'lightcoral';
                    }
                });
                if (selected.value === q.answer) { score++; }
            });
            quizResults.textContent = `Result: You got ${score} out of ${currentQuizData.questions.length} correct!`;
            quizResults.style.color = score === currentQuizData.questions.length ? 'lightgreen' : 'orange';
        });
        if(quizModalOverlay) quizModalOverlay.addEventListener('click', (e) => {
            if (e.target === quizModalOverlay) {
                quizModalOverlay.style.display = 'none';
            }
        });

        if (addNewNoteBtn) addNewNoteBtn.addEventListener('click', () => addNote());
        if (backToListBtn) backToListBtn.addEventListener('click', () => switchView('list'));
        if (searchInput) searchInput.addEventListener('input', renderNoteList);
        if (exportNotesBtn) exportNotesBtn.addEventListener('click', exportNotes);
        const handleInput = () => {
            updateStatus('Typing...', true);
            if (debounceTimer) clearTimeout(debounceTimer);
            debounceTimer = setTimeout(saveNote, 1000);
        };
        if (noteTitleInput) noteTitleInput.addEventListener('input', handleInput);
        if (noteContentTextarea) noteContentTextarea.addEventListener('input', handleInput);
        if (notesList) notesList.addEventListener('click', e => {
            const noteItem = e.target.closest('.note-item');
            if (!noteItem) return;
            const noteId = noteItem.dataset.id;
            if (e.target.closest('.delete-btn')) handleDeleteRequest(noteId);
            else if (e.target.closest('.pin-btn')) togglePin(noteId);
            else openNoteEditor(noteId);
        });
        if (formatToolbar) formatToolbar.addEventListener('click', e => {
            const button = e.target.closest('.format-btn');
            if (button) applyFormat(button.dataset.format);
        });
        if (linkTopicBtn) linkTopicBtn.addEventListener('click', () => {
            if(!noteContentTextarea) return;
            const topicTitle = document.title || 'Current Topic';
            const linkText = `\n\n🔗 Related Topic: [${topicTitle}]`;
            noteContentTextarea.value += linkText;
            saveNote();
        });
        if (chatModeSelector) chatModeSelector.addEventListener('click', (e) => {
            const button = e.target.closest('button');
            if (button && button.dataset.mode) {
                selectedMode = button.dataset.mode;
                chatModeSelector.querySelectorAll('button').forEach(btn => btn.classList.remove('active'));
                button.classList.add('active');
                if (selectedMode === 'custom') {
                    openPromptModal();
                }
                renderChatHistory(selectedMode);
            }
        });
        if (editCustomPromptBtn) editCustomPromptBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            openPromptModal();
        });

        setupNavigator();
        initializeFirebase();
    }

    initialize();
});
